name = "H5Zzstd"
uuid = "f6f2d980-1ec6-471c-a70d-0270e22f1103"
version = "0.1.1"

[deps]
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
HDF5 = "0.17"
CodecZstd = "0.7"
julia = "1.3"
