name = "H5Zlz4"
uuid = "eb20ec05-5464-47b5-ba41-098e3c1068a3"
version = "0.1.1"

[deps]
CodecLz4 = "5ba52731-8f18-5e0d-9241-30f10d1ec561"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
HDF5 = "0.17"
CodecLz4 = "0.4"
julia = "1.3"
